#!/bin/bash

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [ "$GIT_ALLOW_MASTER_PUSH" != 1 -a "$CURRENT_BRANCH" = "master" ];then
    echo "WARN: It's the master branch !!"
    echo 'If you watch git push please set GIT_ALLOW_MASTER_PUSH=1'
    exit 1
fi