[tools]
aws-cli = "latest"
aws-vault = "latest"
delta = "latest"
fzf = "latest"
ghq = "latest"
github-cli = "latest"
kubectl = "latest"
lsd = "latest"
neovim = "latest"
peco = "latest"
ruby = "3.4.2"
starship = "latest"
usage = "latest"

[alias]
neovim = "asdf:https://github.com/richin13/asdf-neovim"
