#!/bin/bash

CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$CURRENT_BRANCH" =~ ^(master|main)$ ]];then
  if [ -z "$ALLOW_GIT_MASTER_PUSH" -a -z "$(git config --get git.allow-master-push)" ];then
    echo -e "\033[31mWARN: It's a master or main branch !!\033[0m"
    echo "Tips: You can skip this warning by setting either of the following:"
    echo "  * \$ALLOW_GIT_MASTER_PUSH=1"
    echo "  * git config --local git.allow-master-push 1"

    # /dev/ttyを使用して確実にキーボード入力を取得
    exec < /dev/tty
    read -p "Do you want to continue? (y/N): " answer
    exec <&-

    if [[ "$answer" != "y" ]]; then
      exit 1
    fi
  fi
fi
